package meetingteam.chatservice.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "RequestMessage")
public class RequestMessage {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String senderId;

    // friend request
    private String recipientId;

    // team request
    private String teamId;

    private String content;

    @DynamoDBRangeKey
    private LocalDateTime createdAt;
}
